"""add_parser_used

Revision ID: adadc40e3834
Revises: cba5e7184ce4
Create Date: 2026-05-02 01:05:18.175204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adadc40e3834'
down_revision: Union[str, None] = 'cba5e7184ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_pages', sa.Column('parser_used', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_pages', 'parser_used')
    # ### end Alembic commands ###
